apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "spring5web.fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "spring5web.name" . }}
data:
  # Variable for environment specific path
  {{- $configFilePath := printf "config/override-%s.properties" .Values.env -}}

  # When the config map is mounted as a volume, these will be created as files.
  override.properties: |-
{{ .Files.Get $configFilePath | indent 4 }}